---
title: 'Homework #1'
author: "Mateusz Kucharzak"
output:
  html_notebook: default
  pdf_document: default
---
1 Create the following numeric vectors
```{r}
v1 <- 1:20
```
```{r}
v2 <- 20:1
```
```{r}
v3 <- c(v1,19:1)
```
```{r}
tmp <- c(7,8,1)
```
```{r}
v4 <- rep(c(4,6,7), times = 10)
```
```{r}
v5 <- rep(c(4,6,7), times = c(11,10,9))
```
```{r}
x <- seq(from = 3, to = 6, by = 0.1)
v6 <- exp(x)*cos(x)
```
```{r}
v7 <- 1:25
v7_wynik <- (2^v7)/v7
```
```{r}
v8 <- 10:100
v8_wynik <- v8^3 + 4*v8^2
sum(v8_wynik)
```
```{r}
v9 <- 1:25
v9_wynik <- ((2^v9)/v9) + (3^v9/v9^2)
sum(v9_wynik)
```
2 Create the follwing character and factor vectors
```{r}
set.seed(123)
v10 <- sample(c(0,1), 1000, TRUE)
```

```{r}
V11 <- factor(v10, levels = c(0,1), labels = c("No","Yes"))
```

```{r}
v12 <- paste0(rep("q", 15),rep(1:5,1,each = 3),rep("s", 15), rep(1:3,5))
```

3 Declare the following matrices
```{r}
wektor_A <- c(3, -3, -2, 1, 2, 6, -2, 1, 3)
A <- matrix(wektor_A, nrow = 3, ncol = 3)
```
```{r}
wektor_B <- c(1, 0, 2, 2, -2, -1)
B <- matrix(wektor_B, nrow = 2, ncol = 3)
```
```{r}
wektor_c <- c(1:4)
C <- matrix(wektor_c, ncol = 2, nrow = 2)
t(C)
```




