---
title: "Zadanie domowe 1"
author: "Ksawery Smoczyński"
output: html_notebook
---

1 Create the following numeric vectors<br>
  • (1, 2, 3, . . . , 20)<br>
  • (20, 19, . . . , 1)<br>
  • (1, 2, 3, . . . , 20, 19, 18, . . . , 1) <br>
  • assign $(7, 8, 1)$ to object tmp <br>
  • $(4, 6, 3, 4, 6, 3, . . . , 4, 6, 3)$ where each element occur 10 times <br>
  • $(4, 6, 3, 4, 6, 3, . . . , 4, 6, 3)$ where 4 occurs 11 times, 6 occurs 10 times and 3 occurs 9 times <br>
  • create a vector $e^xcos(x)$ for vector $x = 3, 3.1, 3.2, ..., 6$ <br>
```{r}
#Z reszta już miałem problemy, latex przerósł.
```
  

Zadanie 1
```{r}
#1.1
seq(1,20)
```
```{r}
#1.2
seq(20,1)
```
```{r}
#1.3
c(1:20, 19:1)
```
```{r}
#1.4
tmp <- c(7,8,1)
```
```{r}
#1.5
rep.int(c(4,6,3),10)
```
```{r}
#1.6
c(rep.int(c(4,6,3),9),4,6,4)
```
```{r}
#1.7
h = seq(3,6,0.1)
exp(h)*cos(h)
```
```{r}
#1.8
i <- seq(1,25)
(2^i)*i
```
```{r}
#1.9
j <- seq(10,100)
sum(((j^3) + (4*(j^2))))
```
```{r}
#1.10
l <- seq(1,25)
sum(((2^l)/l)+ ((3^l)/l))
```


Zadanie 2
```{r}
#2.1
a <- sample(c(0,1), replace = TRUE, size = 100)
```
```{r}
#2.2
b <- factor(a,
            levels = 0:1,
            labels = c("No","Yes"))
```
```{r}
#2.3
for (q in seq(1:5)){
  for(s in seq(1:3))
    cat(paste("q",q,"s",s,","))
}
```


Zadanie 3
```{r}
#3.1
A = matrix(c(3,1,-2,-3,2,1,-2,6,3),nrow = 3,ncol = 3,byrow = T)
A
```
```{r}
#3.2
B = matrix(c(1,2,-2,0,2,-1),nrow = 2,ncol = 3,byrow = T)
B
```
```{r}
#3.3
C = matrix(1:4,2,2,T)
C
```
